version: "3"

services:
  web:
    build: .
    ports:
      - 3000:3000
    # volumes: 
    #   - .:/abcd
    #   # - /abcd/node_modules  
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --port 27017